Validate that all deposit amounts are positive
duality-labs/duality pull request #412
Opened 2023-05-25 22:27 UTC by teddyknox

2023-06-02 04:26 UTC, jcompagni10 requested changes

2023-06-02 04:26 UTC, jcompagni10 commented on x/dex/types/message_deposit.go
isn't this going to error for all 1-sided deposits?

2023-06-07 13:59 UTC, teddyknox commented on x/dex/types/message_deposit.go
No because one sided deposits do not use amounts that are less than 0.

2023-06-08 14:03 UTC, teddyknox commented on x/dex/types/message_deposit.go
Update: you are correct. Updated.

2023-06-08 19:17 UTC, jcompagni10 submitted a review, later dismissed

2023-06-12 10:40 UTC, merged